defaults:
  - data: ETTm1
  - model: Dlinear
  - optimization: default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


# forecasting task
seq_len: 96
label_len: 48
pred_len: 96
features: M
target: OT


# training related
benchmark: False
fast_dev_run: False 
limit_train_batches: 1.0
limit_val_batches: 1.0
exp_num: 9999
seed: 41
gpu_id: 0
use_amp: true

save_output_path: outputs/${data.data_name}/EXP${exp_num}
hydra:
  run:
    dir: ${save_output_path}