num_workers: 4
batch_size: 32
optimizer:
  learning_rate: 0.0001
  lradj: type1

callbacks:
  monitor: val_loss
  mode: min
  max_epochs: 40
  patience: 3
  min_delta: 0
  check_val_every_n_epoch: 1

  

